<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>1.3.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <SCP_SL_MANAGED Condition="'$(SCP_SL_MANAGED)' == ''">C:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed</SCP_SL_MANAGED>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <Reference Include="Assembly-CSharp" HintPath="$(SCP_SL_MANAGED)/Assembly-CSharp.dll" Private="false" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="$(SCP_SL_MANAGED)/Assembly-CSharp-firstpass.dll" Private="false" />
    <Reference Include="LabApi" HintPath="$(SCP_SL_MANAGED)/LabApi.dll" Private="false" />
    <Reference Include="Mirror" HintPath="$(SCP_SL_MANAGED)/Mirror.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(SCP_SL_MANAGED)/UnityEngine.CoreModule.dll" Private="false" />
  </ItemGroup>
</Project>
